package org.vamdc.xsams.functions;

import org.vamdc.xsams.common.ArgumentType;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ArgumentsType extends org.vamdc.xsams.schema.ArgumentsType {
	
	public ArgumentsType(){
		super();
	}

	public ArgumentsType(ArgumentType argument){
		super();
		this.getArguments().add(argument);
	}
	
}

