package org.vamdc.xsams.functions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FunctionParameterType extends org.vamdc.xsams.schema.FunctionParameterType {
	
	public FunctionParameterType(){
		super();
	}

}

