package org.vamdc.xsams.functions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Functions extends org.vamdc.xsams.schema.Functions {
	
	public Functions(){
		super();
	}

}

