package org.vamdc.xsams.functions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FunctionParametersType extends org.vamdc.xsams.schema.FunctionParametersType {
	
	public FunctionParametersType(){
		super();
	}

}

