package org.vamdc.xsams.functions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FunctionType extends org.vamdc.xsams.schema.FunctionType {
	
	public FunctionType(){
		super();
	}

}

