package org.vamdc.xsams.functions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FunctionParameterType extends org.vamdc.xsams.schema.FunctionParameterType {
	
	public FunctionParameterType(){
		super();
	}
	
	public FunctionParameterType(String name, String units, String description){
		super();
		this.setName(name);
		this.setUnits(units);
		this.setDescription(description);
	}

}

