package org.vamdc.xsams;

import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.Unmarshaller;

/**
Base class for autogenerated JAXB classes, 
provides handy method for parent referencing
*/
@XmlTransient
public class BaseClass{
	@XmlTransient
	private Object parent;
	
	public Object getParent(){
		return this.parent;
	}
	
	public void afterUnmarshal(Unmarshaller u, Object parent) {
		this.parent = parent;
	}

}
