package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AbsorptionCrossSectionType extends org.vamdc.xsams.schema.AbsorptionCrossSectionType {
	
	public AbsorptionCrossSectionType(){
		super();
	}

}

