package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class BandAssignmentType extends org.vamdc.xsams.schema.BandAssignmentType {
	
	public BandAssignmentType(){
		super();
	}

}

