package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class BroadeningType extends org.vamdc.xsams.schema.BroadeningType {
	
	public BroadeningType(){
		super();
	}

}

