package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class EnergyWavelengthType extends org.vamdc.xsams.schema.EnergyWavelengthType {
	
	public EnergyWavelengthType(){
		super();
	}

}

