package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class LineshapeType extends org.vamdc.xsams.schema.LineshapeType {
	
	public LineshapeType(){
		super();
	}

}

