package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ModesType extends org.vamdc.xsams.schema.ModesType {
	
	public ModesType(){
		super();
	}

}

