package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class RadiativeTransitionType extends org.vamdc.xsams.schema.RadiativeTransitionType {
	
	public RadiativeTransitionType(){
		super();
	}

}

