package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Radiative extends org.vamdc.xsams.schema.Radiative {
	
	public Radiative(){
		super();
	}

}

