package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class RadiativeTransitionProbabilityType extends org.vamdc.xsams.schema.RadiativeTransitionProbabilityType {
	
	public RadiativeTransitionProbabilityType(){
		super();
	}

}

