package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SatelliteLineProperties extends org.vamdc.xsams.schema.SatelliteLineProperties {
	
	public SatelliteLineProperties(){
		super();
	}

}

