package org.vamdc.xsams.process.radiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ShiftingType extends org.vamdc.xsams.schema.ShiftingType {
	
	public ShiftingType(){
		super();
	}

}

