package org.vamdc.xsams.sources;

/**
Autogenerated customizeable class for user's handy methods
*/
public class EditorsType extends org.vamdc.xsams.schema.EditorsType {
	
	public EditorsType(){
		super();
	}

}

