package org.vamdc.xsams.sources;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Sources extends org.vamdc.xsams.schema.Sources {
	
	public Sources(){
		super();
	}

}

