package org.vamdc.xsams.methods;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Methods extends org.vamdc.xsams.schema.Methods {
	
	public Methods(){
		super();
	}

}

