package org.vamdc.xsams.methods;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MethodType extends org.vamdc.xsams.schema.MethodType {
	
	public MethodType(){
		super();
	}

}

