package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Atoms extends org.vamdc.xsams.schema.Atoms {
	
	public Atoms(){
		super();
	}

}

