package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicCoreType extends org.vamdc.xsams.schema.AtomicCoreType {
	
	public AtomicCoreType(){
		super();
	}

}

