package org.vamdc.xsams.species.atoms;

import org.vamdc.xsams.schema.AtomicIonType;
import org.vamdc.xsams.schema.IsotopeType;
import org.vamdc.xsams.util.SpeciesInterface;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomType extends org.vamdc.xsams.schema.AtomType implements SpeciesInterface{
	
	public AtomType(){
		super();
	}
	/**
	 * Get species ID from my ion record, do nothing if I have more than one ion or isotope, or don't have required structure.
	 */
	@Override
	public String getSpeciesID() {
		if (this.getIsotopes().size()!=1)
			return null;
		IsotopeType isot = this.getIsotopes().get(0);
		AtomicIonType iot = null;
		if (isot!=null && isot.getIons().size()==1 && (iot=isot.getIons().get(0))!=null)
			return iot.getSpeciesID();
		else
		return null;
	}

	@Override
	public void setSpeciesID(String speciesID) {
		if (this.getIsotopes().size()!=1)
			return;
		IsotopeType isot = this.getIsotopes().get(0);
		AtomicIonType iot = null;
		if (isot!=null && isot.getIons().size()==1 && (iot=isot.getIons().get(0))!=null)
			iot.setSpeciesID(speciesID);
	}
}

