package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicQuantumNumbersType extends org.vamdc.xsams.schema.AtomicQuantumNumbersType {
	
	public AtomicQuantumNumbersType(){
		super();
	}

}

