package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicCompositionType extends org.vamdc.xsams.schema.AtomicCompositionType {
	
	public AtomicCompositionType(){
		super();
	}

}

