package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicComponentType extends org.vamdc.xsams.schema.AtomicComponentType {
	
	public AtomicComponentType(){
		super();
	}

}

