package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicIonType extends org.vamdc.xsams.schema.AtomicIonType {
	
	public AtomicIonType(){
		super();
	}

}

