package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicNumericalDataType extends org.vamdc.xsams.schema.AtomicNumericalDataType {
	
	public AtomicNumericalDataType(){
		super();
	}

}

