package org.vamdc.xsams.species.atoms;

import org.vamdc.xsams.util.StateInterface;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AtomicStateType extends org.vamdc.xsams.schema.AtomicStateType implements StateInterface{
	
	public AtomicStateType(){
		super();
	}

}

