package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ConfigurationType extends org.vamdc.xsams.schema.ConfigurationType {
	
	public ConfigurationType(){
		super();
	}

}

