package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class IsotopeParametersType extends org.vamdc.xsams.schema.IsotopeParametersType {
	
	public IsotopeParametersType(){
		super();
	}

}

