package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class IsotopeType extends org.vamdc.xsams.schema.IsotopeType {
	
	public IsotopeType(){
		super();
	}

}

