package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class JjCouplingType extends org.vamdc.xsams.schema.JjCouplingType {
	
	public JjCouplingType(){
		super();
	}

}

