package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class JKCouplingType extends org.vamdc.xsams.schema.JKCouplingType {
	
	public JKCouplingType(){
		super();
	}

}

