package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class LKCouplingType extends org.vamdc.xsams.schema.LKCouplingType {
	
	public LKCouplingType(){
		super();
	}

}

