package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class LSCouplingType extends org.vamdc.xsams.schema.LSCouplingType {
	
	public LSCouplingType(){
		super();
	}

}

