package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ShellsType extends org.vamdc.xsams.schema.ShellsType {
	
	public ShellsType(){
		super();
	}

}

