package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ShellType extends org.vamdc.xsams.schema.ShellType {
	
	public ShellType(){
		super();
	}

}

