package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ShellPairType extends org.vamdc.xsams.schema.ShellPairType {
	
	public ShellPairType(){
		super();
	}

}

