package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SuperShellType extends org.vamdc.xsams.schema.SuperShellType {
	
	public SuperShellType(){
		super();
	}

}

