package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SuperConfigurationType extends org.vamdc.xsams.schema.SuperConfigurationType {
	
	public SuperConfigurationType(){
		super();
	}

}

