package org.vamdc.xsams.species.atoms;

/**
Autogenerated customizeable class for user's handy methods
*/
public class TermType extends org.vamdc.xsams.schema.TermType {
	
	public TermType(){
		super();
	}

}

