package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class CharacterisationType extends org.vamdc.xsams.schema.CharacterisationType {
	
	public CharacterisationType(){
		super();
	}

}

