package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MolecularChemicalSpeciesType extends org.vamdc.xsams.schema.MolecularChemicalSpeciesType {
	
	public MolecularChemicalSpeciesType(){
		super();
	}

}

