package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Molecules extends org.vamdc.xsams.schema.Molecules {
	
	public Molecules(){
		super();
	}

}

