package org.vamdc.xsams.species.molecules;

import org.vamdc.xsams.util.SpeciesInterface;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MoleculeType extends org.vamdc.xsams.schema.MoleculeType implements SpeciesInterface {
	
	public MoleculeType(){
		super();
	}

}

