package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MolecularStateCharacterisationType extends org.vamdc.xsams.schema.MolecularStateCharacterisationType {
	
	public MolecularStateCharacterisationType(){
		super();
	}

}

