package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MoleculeStructureType extends org.vamdc.xsams.schema.MoleculeStructureType {
	
	public MoleculeStructureType(){
		super();
	}

}

