package org.vamdc.xsams.species.molecules;

import org.vamdc.xsams.util.StateInterface;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MolecularStateType extends org.vamdc.xsams.schema.MolecularStateType implements StateInterface{
	
	public MolecularStateType(){
		super();
	}

}

