package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MolecularPropertiesType extends org.vamdc.xsams.schema.MolecularPropertiesType {
	
	public MolecularPropertiesType(){
		super();
	}

}

