package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class NormalModesType extends org.vamdc.xsams.schema.NormalModesType {
	
	public NormalModesType(){
		super();
	}

}

