package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class NormalModeType extends org.vamdc.xsams.schema.NormalModeType {
	
	public NormalModeType(){
		super();
	}

}

