package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ReferencedTextType extends org.vamdc.xsams.schema.ReferencedTextType {
	
	public ReferencedTextType(){
		super();
	}

	public ReferencedTextType(String value){
		super();
		this.setValue(value);
	}
	
}

