package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class StateExpansionType extends org.vamdc.xsams.schema.StateExpansionType {
	
	public StateExpansionType(){
		super();
	}

}

