package org.vamdc.xsams.species.molecules;

/**
Autogenerated customizeable class for user's handy methods
*/
public class StateCoeffType extends org.vamdc.xsams.schema.StateCoeffType {
	
	public StateCoeffType(){
		super();
	}

}

