package org.vamdc.xsams.species.solids;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MaterialType extends org.vamdc.xsams.schema.MaterialType {
	
	public MaterialType(){
		super();
	}

}

