package org.vamdc.xsams.species.solids;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MaterialComponentType extends org.vamdc.xsams.schema.MaterialComponentType {
	
	public MaterialComponentType(){
		super();
	}

}

