package org.vamdc.xsams.species.solids;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MaterialCompositionType extends org.vamdc.xsams.schema.MaterialCompositionType {
	
	public MaterialCompositionType(){
		super();
	}

}

