package org.vamdc.xsams.species.solids;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Solids extends org.vamdc.xsams.schema.Solids {
	
	public Solids(){
		super();
	}

}

