package org.vamdc.xsams.species.solids;

import org.vamdc.xsams.util.SpeciesInterface;
import org.vamdc.xsams.util.StateInterface;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SolidType extends org.vamdc.xsams.schema.SolidType implements StateInterface,SpeciesInterface{
	
	public SolidType(){
		super();
	}

	@Override
	public String getStateID() {
		return this.getSpeciesID();
	}

	@Override
	public void setStateID(String stateID) {
		
	}

	
}

