package org.vamdc.xsams.environments;

/**
Autogenerated customizeable class for user's handy methods
*/
public class CompositionType extends org.vamdc.xsams.schema.CompositionType {
	
	public CompositionType(){
		super();
	}

}

