package org.vamdc.xsams.environments;

/**
Autogenerated customizeable class for user's handy methods
*/
public class EnvironmentType extends org.vamdc.xsams.schema.EnvironmentType {
	
	public EnvironmentType(){
		super();
	}

}

