package org.vamdc.xsams.environments;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Environments extends org.vamdc.xsams.schema.Environments {
	
	public Environments(){
		super();
	}

}

