package org.vamdc.xsams.environments;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ReferencedSpeciesType extends org.vamdc.xsams.schema.ReferencedSpeciesType {
	
	public ReferencedSpeciesType(){
		super();
	}

}

