package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class AccuracyType extends org.vamdc.xsams.schema.AccuracyType {
	
	public AccuracyType(){
		super();
	}

}

