package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ArgumentType extends org.vamdc.xsams.schema.ArgumentType {
	
	public ArgumentType(){
		super();
	}

}

