package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ArgumentType extends org.vamdc.xsams.schema.ArgumentType {
	
	public ArgumentType(){
		super();
	}

	public ArgumentType(String name, String units, String description){
		super();
		this.setName(name);
		this.setDescription(description);
		this.setUnits(units);
	}
	
}

