package org.vamdc.xsams.common;

import org.vamdc.xsams.schema.ElementSymbolType;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ChemicalElementType extends org.vamdc.xsams.schema.ChemicalElementType {
	
	public ChemicalElementType(){
		super();
	}
	
	/**
	 * Value constructor
	 * @param charge nuclear charge, integer
	 * @param symbol optional element symbol
	 */
	public ChemicalElementType(int charge, String symbol){
		super();
		if (symbol!=null)
			this.setElementSymbol(ElementSymbolType.valueOf(symbol.toUpperCase()));
		this.setNuclearCharge(charge);
	}

}

