package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataSetType extends org.vamdc.xsams.schema.DataSetType {
	
	public DataSetType(){
		super();
	}

}

