package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataSeriesType extends org.vamdc.xsams.schema.DataSeriesType {
	
	public DataSeriesType(){
		super();
	}

}

