package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataSetsType extends org.vamdc.xsams.schema.DataSetsType {
	
	public DataSetsType(){
		super();
	}

}

