package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataFuncType extends org.vamdc.xsams.schema.DataFuncType {
	
	public DataFuncType(){
		super();
	}

}

