package org.vamdc.xsams.common;

import java.util.Collection;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataSetsType extends org.vamdc.xsams.schema.DataSetsType {
	
	public DataSetsType(){
		super();
	}

	public DataSetsType(Collection<DataSetType> datasets){
		super();
		this.getDataSets().addAll(datasets);
	}
	
	public DataSetsType(DataSetType dataset){
		super();
		this.getDataSets().add(dataset);
	}
	
}

