package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class DataListType extends org.vamdc.xsams.schema.DataListType {
	
	public DataListType(){
		super();
	}

}

