package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ExpressionType extends org.vamdc.xsams.schema.ExpressionType {
	
	public ExpressionType(){
		super();
	}

}

