package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FitDataType extends org.vamdc.xsams.schema.FitDataType {
	
	public FitDataType(){
		super();
	}

}

