package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class FitParametersType extends org.vamdc.xsams.schema.FitParametersType {
	
	public FitParametersType(){
		super();
	}

}

