package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class LifeTimeType extends org.vamdc.xsams.schema.LifeTimeType {
	
	public LifeTimeType(){
		super();
	}

}

