package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class LinearSequenceType extends org.vamdc.xsams.schema.LinearSequenceType {
	
	public LinearSequenceType(){
		super();
	}

}

