package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MatrixType extends org.vamdc.xsams.schema.MatrixType {
	
	public MatrixType(){
		super();
	}

}

