package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class MixingCoefficientType extends org.vamdc.xsams.schema.MixingCoefficientType {
	
	public MixingCoefficientType(){
		super();
	}

}

