package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class NamedDataType extends org.vamdc.xsams.schema.NamedDataType {
	
	public NamedDataType(){
		super();
	}

}

