package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class OrbitalAngularMomentumType extends org.vamdc.xsams.schema.OrbitalAngularMomentumType {
	
	public OrbitalAngularMomentumType(){
		super();
	}

}

