package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class PartitionFunctionType extends org.vamdc.xsams.schema.PartitionFunctionType {
	
	public PartitionFunctionType(){
		super();
	}

}

