package org.vamdc.xsams.common;

import java.util.Collection;

import org.vamdc.xsams.schema.ObjectFactory;
import org.vamdc.xsams.schema.SourceType;

/**
Autogenerated customizeable class for user's handy methods
*/
public class PrimaryType extends org.vamdc.xsams.schema.PrimaryType {
	
	public PrimaryType(){
		super();
	}

	public void addSource(SourceType source){
		ObjectFactory of = new ObjectFactory();
		this.getSourceReves().add(of.createPrimaryTypeSourceRef(source));
	}
	
	public void addSources(Collection<SourceType> sources){
		for (SourceType source:sources){
			this.addSource(source);
		}
	}
	
}

