package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SimpleDataTableType extends org.vamdc.xsams.schema.SimpleDataTableType {
	
	public SimpleDataTableType(){
		super();
	}

}

