package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class SpeciesStateRefType extends org.vamdc.xsams.schema.SpeciesStateRefType {
	
	public SpeciesStateRefType(){
		super();
	}

}

