package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ValueType extends org.vamdc.xsams.schema.ValueType {
	
	public ValueType(){
		super();
	}

	/**
	 * Handy constructor
	 * @param value
	 * @param units
	 */
	public ValueType(Double value, String units) {
		super();
		this.setValue(value);
		this.setUnits(units);
	}
	
}

