package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class VectorsType extends org.vamdc.xsams.schema.VectorsType {
	
	public VectorsType(){
		super();
	}

}

