package org.vamdc.xsams.common;

/**
Autogenerated customizeable class for user's handy methods
*/
public class VectorType extends org.vamdc.xsams.schema.VectorType {
	
	public VectorType(){
		super();
	}

}

