package org.vamdc.xsams.process.nonradiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class NonRadiative extends org.vamdc.xsams.schema.NonRadiative {
	
	public NonRadiative(){
		super();
	}

}

