package org.vamdc.xsams.process.nonradiative;

/**
Autogenerated customizeable class for user's handy methods
*/
public class NonRadiativeTransitionType extends org.vamdc.xsams.schema.NonRadiativeTransitionType {
	
	public NonRadiativeTransitionType(){
		super();
	}

}

