package org.vamdc.xsams.process.collisions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Collisions extends org.vamdc.xsams.schema.Collisions {
	
	public Collisions(){
		super();
	}

}

