package org.vamdc.xsams.process.collisions;

import org.vamdc.xsams.schema.CodeType;

/**
Autogenerated customizeable class for user's handy methods
*/
public class CollisionalProcessClassType extends org.vamdc.xsams.schema.ProcessClassType {
	
	public CollisionalProcessClassType(){
		super();
	}
	
	public CollisionalProcessClassType(String... codes){
		super();
		for (String code:codes){
			try{
			this.getCodes().add(CodeType.valueOf(code.toUpperCase()));
			}catch (IllegalArgumentException e){
			}
		}
	}

}

