package org.vamdc.xsams.process.collisions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class CollisionalProcessClassType extends org.vamdc.xsams.schema.CollisionalProcessClassType {
	
	public CollisionalProcessClassType(){
		super();
	}
	
	public CollisionalProcessClassType(String... codes){
		super();
		for (String code:codes){
			this.getCodes().add(code);
		}
	}

}

