package org.vamdc.xsams.process.collisions;

/**
Autogenerated customizeable class for user's handy methods
*/
public class CollisionalTransitionType extends org.vamdc.xsams.schema.CollisionalTransitionType {
	
	public CollisionalTransitionType(){
		super();
	}

}

