package org.vamdc.xsams.species.particles;

/**
Autogenerated customizeable class for user's handy methods
*/
public class ParticlePropertiesType extends org.vamdc.xsams.schema.ParticlePropertiesType {
	
	public ParticlePropertiesType(){
		super();
	}

}

