package org.vamdc.xsams.species.particles;

/**
Autogenerated customizeable class for user's handy methods
*/
public class Particles extends org.vamdc.xsams.schema.Particles {
	
	public Particles(){
		super();
	}

}

